import {StyleSheet, Dimensions} from 'react-native';

export const GlobalStyles = StyleSheet.create({
  screen: {
    backgroundColor: '#292732',
    flex: 1,
    justifyContent: 'flex-start',
    alignContent: 'center',
  },
  splash: {
    backgroundColor: '#292732',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  psscreen: {
    backgroundColor: '#292732',
    flex: 1,
    justifyContent: 'flex-start',
    alignContent: 'center',
  },
  Modalcreen: {
    backgroundColor: '#292732',
    flex: 1,
    justifyContent: 'flex-start',
    alignContent: 'center',
    height: 300,
    maxHeight: 400,
    //opacity: 0.7,
    borderRadius: 20,
  },
  maincreen: {
    backgroundColor: '#E4E4E4',
    flex: 1,
    justifyContent: 'flex-start',
    alignContent: 'center',
    //marginTop: 20
  },
  loginScreen: {
    backgroundColor: '#ee1c28',
    flex: 1,
    justifyContent: 'flex-start',
    alignContent: 'center',
    //marginTop: 20
  },
  productBtn: {
    alignSelf: 'center',
    marginVertical: 4,
    borderRadius: 15,
    //width: Dimensions.get('window').width * 0.8,
    fontFamily: 'poppins_bold',
  },
  BtnStyle: {
    alignSelf: 'center',
    marginVertical: 4,
    borderRadius: 15,
    width: Dimensions.get('window').width * 0.8,
    fontFamily: 'poppins_bold',
  },
  AddBtnStyle: {
    alignSelf: 'center',
    //marginVertical: 20,
    width: '45%',
    //marginHorizontal:20
  },
  AddBtnStyle2: {
    alignSelf: 'center',
    //marginVertical: 20,
    width: '45%',
    marginLeft: 25,
    //marginHorizontal:20
  },
  contactBtns: {
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'space-between',
    marginHorizontal: 15,
    marginTop: 20,
  },
  txt: {
    alignSelf: 'center',
    marginVertical: 20,
    fontFamily: 'Montserrat-Bold',
    marginHorizontal: 10,
    textAlign: 'center',
  },
  txtSettings: {
    alignSelf: 'center',
    marginTop: 20,
    fontFamily: 'Montserrat-Bold',
    marginHorizontal: 10,
    textAlign: 'center',
  },
  labelSetting: {
    alignSelf: 'center',
    marginVertical: 15,
    fontFamily: 'Montserrat-Bold',
    marginHorizontal: 10,
    textAlign: 'center',
  },
  secondtxtSettings: {
    alignSelf: 'center',
    //marginVertical: 20,
    fontFamily: 'Montserrat-Bold',
    marginHorizontal: 10,
    textAlign: 'center',
  },
  txtRecovery: {
    alignSelf: 'center',
    marginVertical: 20,
    //fontFamily: "Montserrat-Bold",
    justifyContent: 'center',
    marginHorizontal: 25,
    textAlign: 'center',
  },
  labelRecovery: {
    alignSelf: 'center',
    marginVertical: 20,
    //fontFamily: "Montserrat-Bold",
    justifyContent: 'center',
    //marginHorizontal:25,
    textAlign: 'center',
  },
  txtDrawer: {
    alignSelf: 'center',
    marginVertical: 2,
    //fontFamily: "Montserrat-Bold",
    paddingLeft: 2,
  },
  txtRecovery: {
    alignSelf: 'center',
    marginVertical: 20,
    fontFamily: 'Montserrat-Bold',
    justifyContent: 'center',
    marginHorizontal: 25,
    textAlign: 'center',
  },
  labelRecovery: {
    alignSelf: 'center',
    marginVertical: 20,
    fontFamily: 'Montserrat-Bold',
    justifyContent: 'center',
    //marginHorizontal:25,
    textAlign: 'center',
  },
  txtDrawer: {
    alignSelf: 'center',
    marginVertical: 2,
    fontFamily: 'Montserrat-Bold',
    paddingLeft: 2,
  },
  inputItem: {
    //backgroundColor: 'transparent',
    //paddingHorizontal:150,
    width: Dimensions.get('window').width * 0.9,
    alignSelf: 'center',
    marginBottom: 2,
    alignContent: 'flex-start',

    //borderRadius: 30,
  },
  selectItem: {
    backgroundColor: '#292732',
    //paddingHorizontal:150,
    width: '90%',
    alignSelf: 'center',
    marginTop: 8,
    alignContent: 'flex-start',
    borderRadius: 30,
    color: 'white',
    borderWidth: 0.5,
    borderColor: 'white',
  },
  bordardingTitle: {
    fontFamily: 'Montserrat-Regular',
    textAlign: 'center',
    marginTop: 60,
  },
  newsTitle: {
    fontFamily: 'poppins_medium',
    color: 'white',
    fontSize: 18,
  },
  iconStyle: {
    fontFamily: 'poppins_medium',
    color: 'white',
    fontSize: 26,
  },
  bordardingText: {
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    color: 'white',
    paddingHorizontal: 20,
    fontWeight: 'bold',
    marginVertical: 30,
  },
  phraseLabel: {
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    color: 'white',
    //paddingHorizontal:20,
    //fontWeight:'bold',
    marginVertical: 30,
  },
  chartText: {
    fontFamily: 'Montserrat-Regular',
    textAlign: 'center',
    color: '#ee1c28',
    paddingHorizontal: 20,
    fontWeight: 'bold',
    marginVertical: 30,
  },
  label: {
    alignSelf: 'center',
    marginVertical: 12,
    fontSize: 17,
    //marginRight: 30,
    fontFamily: 'poppins_bold',
    color: '#ee1c28',
  },
  InputLabel: {
    alignSelf: 'flex-start',
    //marginVertical: 2,
    //fontSize:10,
    //marginRight: 30,
    fontFamily: 'poppins_medium',
    color: 'black',
  },
  errorLabel: {
    alignSelf: 'flex-start',
    //marginVertical: 2,
    //fontSize:10,
    //marginRight: 30,
    fontFamily: 'poppins_medium',
    color: 'red',
  }, //
  label2: {
    alignSelf: 'center',
    paddingTop: 20,
    marginHorizontal: 10,
    textAlign: 'center',
    fontFamily: 'poppins_medium',
    //fontFamily:'Montserrat-Regular',
    //marginRight:30
  },
  register: {
    alignSelf: 'flex-start',
    //paddingTop: 20,
    //marginHorizontal: 10,
    textAlign: 'left',
    fontFamily: 'poppins_medium',
    //marginRight:30
  },
  headerStyle: {
    backgroundColor: '#ee1c28',
    height: Dimensions.get('window').height * 0.075,
  },
  btnLabel: {
    alignSelf: 'center',
    //paddingTop: 20,
    //marginHorizontal: 10,
    textAlign: 'center',
    fontFamily: 'poppins_medium',
    color: 'white',
    //marginRight:30
  },
  label3: {
    alignSelf: 'center',
    paddingTop: 5,
    //fontFamily:'Montserrat-Regular',
    //marginRight:30
  },
  walletBtn: {
    marginTop: 10,
    alignSelf: 'center',
    fontFamily: 'poppins_medium',
    //fontFamily:'Montserrat-Regular',
    //height:80
  },
  mainLbl: {
    alignSelf: 'center',
    marginVertical: 20,
    fontSize: 35,
    color: '#56e39c',
  },
  walletCard1: {
    margin: 5,
    height: 80,
    width: '47%',
    backgroundColor: '#313342',
    borderRadius: 15,
    //opacity: 0.7,
    alignContent: 'center',
    alignItems: 'center',
  },
  walletCard2: {
    margin: 5,
    height: 80,
    backgroundColor: '#313342',
    borderRadius: 15,
    //opacity: 0.7,
    justifyContent: 'space-between',
    alignContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  TextShadowStyle: {
    textShadowColor: '#000',
    textShadowOffset: {width: 0, height: 6},
    textShadowRadius: 10,
  },
  loginCard: {
    alignSelf: 'center',
    //marginHorizontal: 10,
    borderColor: 'black',
    borderWidth: 1,
  },
  productLabel: {
    marginTop: 5,
    alignSelf: 'center',
    fontFamily: 'poppins_medium',
    fontSize:20
  },
  productPrice: {
    marginTop: 2,
    alignSelf: 'center',
    fontFamily: 'poppins_black',
  },
});
